swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: mail
    auth_mode: login
    port: 587
    encryption: ssl
    host: smtp.gmail.com
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
