<?php

namespace ContainerI3wh3dQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CreateFormType' shared autowired service.
     *
     * @return \App\Form\CreateFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\CreateFormType.php';

        return $container->privates['App\\Form\\CreateFormType'] = new \App\Form\CreateFormType();
    }
}
