<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMSZaG8j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMSZaG8j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMSZaG8j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMSZaG8j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMSZaG8j\App_KernelDevDebugContainer([
    'container.build_hash' => 'MSZaG8j',
    'container.build_id' => 'b84da89c',
    'container.build_time' => 1609868136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMSZaG8j');
