<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUUsHVOR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUUsHVOR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUUsHVOR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUUsHVOR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUUsHVOR\App_KernelDevDebugContainer([
    'container.build_hash' => 'UUsHVOR',
    'container.build_id' => 'be953580',
    'container.build_time' => 1609889272,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUUsHVOR');
